apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spike-api
  namespace: spike
spec:
  ingressClassName: nginx
  rules:
    - host: spike-api.10.255.42.75.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spike-api
                port:
                  number: 8000
