apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spike-model-pvc
  namespace: spike
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
