apiVersion: v1
kind: Service
metadata:
  name: spike-api
  namespace: spike
  labels:
    app: spike-api
spec:
  type: ClusterIP
  selector:
    app: spike-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
